<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.third.li</groupId>
        <artifactId>erp-app</artifactId>
        <version>1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>erp-app-openapi</artifactId>
    <packaging>jar</packaging>
    <name>erp-app-openapi</name>
    <description>Deployable end: erp-app-openapi</description>

    <dependencies>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-shared-kernel</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-kernel</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-web</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-messaging</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-platform-integration</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-system</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-teaching-plan</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-exam</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-attendance</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-grade</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-student</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-enrollment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-dormitory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-moral-education</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-hr</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-finance</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-asset</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-employment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-evaluation</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-message</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-iot-terminal</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-quality</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-workflow</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.third.li</groupId>
            <artifactId>erp-integration</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>