<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.third.li</groupId>
        <artifactId>agentscope</artifactId>
        <version>1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>agentscope-workspace</artifactId>
    <packaging>pom</packaging>
    <name>agentscope-workspace</name>
    <description>⑤ 工作区与沙箱 ★</description>

    <modules>
        <module>agentscope-local-workspace</module>
        <module>agentscope-docker-sandbox</module>
        <module>agentscope-remote-filesystem</module>
        <module>agentscope-workspace-snapshot</module>
        <module>agentscope-plan-mode</module>
    </modules>

</project>