apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}