<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.third.li</groupId>
        <artifactId>agentscope</artifactId>
        <version>1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>agentscope-service</artifactId>
    <packaging>pom</packaging>
    <name>agentscope-service</name>
    <description>⑦ 服务与渠道 ★</description>

    <modules>
        <module>agentscope-gateway</module>
        <module>agentscope-chatui</module>
        <module>agentscope-channels</module>
        <module>agentscope-scheduler</module>
        <module>agentscope-a2a</module>
    </modules>

</project>