<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.third.li</groupId>
        <artifactId>langchain4j</artifactId>
        <version>1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>langchain4j-memory</artifactId>
    <packaging>pom</packaging>
    <name>langchain4j-memory</name>

    <modules>
        <module>langchain4j-chat-memory</module>
        <module>langchain4j-persistent-memory</module>
        <module>langchain4j-multi-user</module>
    </modules>

</project>